version: 2
jobs:
  build:
    docker:
    - image: circleci/node:9.9.0

    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: npm run start
          command: npm run start
      - run:
          name: npm run build
          command: npm run build
